
services:
    # imagem do projeto
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - postgres
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # postgres
    postgres:
        image: postgres:13
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}  # A variável DB_USERNAME deve estar definida corretamente
            POSTGRES_PASSWORD: ${DB_PASSWORD}  # A variável DB_PASSWORD deve estar definida corretamente
            POSTGRES_DB: ${DB_DATABASE}  # A variável DB_DATABASE deve estar definida corretamente
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - laravel
    # Keycloak
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: laravel_keycloak
        environment:
            - DB_VENDOR=postgres
            - DB_ADDR=postgres
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=keycloak
            - KC_BOOTSTRAP_ADMIN_USERNAME=admin
            - KC_BOOTSTRAP_ADMIN_PASSWORD=admin123
        ports:
            - "8888:8080"
        command: [ "start-dev" ]
        depends_on:
            - postgres
        networks:
            - laravel
volumes:
    postgres-data:
networks:
    laravel:
        driver: bridge
