<?php

return [
    'KEYCLOAK_REALM' => env('KEYCLOAK_REALM'),
    'KEYCLOAK_AUTH_SERVER_URL' => env('KEYCLOAK_AUTH_SERVER_URL'),
    'KEYCLOAK_CLIENT_ID' => env('KEYCLOAK_CLIENT_ID'),
    'KEYCLOAK_REDIRECT_URI' => env('KEYCLOAK_REDIRECT_URI'),
    'KEYCLOAK_SSL_REQUIRED' => env('KEYCLOAK_SSL_REQUIRED'),
];
